# Generated by Django 5.1.3 on 2024-11-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
